### ISSUE TITLE
Code watching / autogeneration of docs

### ISSUE THREAD

**Issue by atroche** [gdeer81/marginalia#144] opened 2015-01-16 00:54 UTC
Hey guys,

I'd love it if I could run something like `lein marg --watch` and it would watch for changes to my source files and regenerate docs (rather than having to run it manually every time). Would this be a hard change? Or does the functionality already exist and I somehow missed it?

**Comment by benjamin-bader** [comment] 2015-01-16 01:16
Hi, this is an exact duplicate of #143, which you submitted and which I closed.  In my comment, please note that I suggested a way to do this without adding any new code.  I also mentioned that this is the wrong Github project for Leiningen/Marginalia functionality.

At present, this feature does not exist in lein-marginalia; I'm not a committer there, but I'm sure that a pull request with this feature would be welcome.

**Closed by benjamin-bader** 2015-01-16 01:16 UTC

**Comment by atroche** [comment] 2015-01-16 01:32
Haha, sorry Ben, clearly having an absent minded morning. Thanks for your
patience!

On 16 January 2015 at 12:16, Ben Bader <notifications@github.com> wrote:

> Closed #144 <https://github.com/gdeer81/marginalia/issues/144>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdeer81/marginalia/issues/144#event-219825785>.
>



-- 
-- Alistair
